build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\projects\basercms

environment:
  global:
    PHP: C:\tools\php
    DB: 'sqlite'

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\tools\php -> appveyor.yml
  - C:\projects\basercms\vendors -> composer.json
  - C:\Users\appveyor\AppData\Local\Composer -> composer.json

init:
  - SET PATH=%PHP%;%PATH%
  - git config --global core.autocrlf input

install:
  - cinst -y php
  - cd %PHP%
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_sqlite3.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist --no-interaction --dev
  - cd app
  - php ./Console/cake.php bc_manager checkenv
  - php ./Console/cake.php bc_manager install "http://localhost" %DB% "admin" "basercms" "webmaster@example.org" --host "localhost" --database "basercms" --login "basercms" --password "basercms" --prefix "mysite_" --smarturl "true"  --data "nada-icons.default"

test_script:
  - php ./Console/cake.php baser_test baser BcAll --debug